"""second migration

Revision ID: f50f41e40e2f
Revises: 750004d9bd91
Create Date: 2020-12-07 22:21:35.193787

"""

# revision identifiers, used by Alembic.
revision = 'f50f41e40e2f'
down_revision = '750004d9bd91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unit', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'user_id')
    # ### end Alembic commands ###
